# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.api.email_api import EmailApi  # noqa: E501
from nexus_sdk.rest import ApiException


class TestEmailApi(unittest.TestCase):
    """EmailApi unit test stubs"""

    def setUp(self):
        self.api = EmailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_email_configuration(self):
        """Test case for delete_email_configuration

        Disable and clear the email configuration  # noqa: E501
        """
        pass

    def test_get_email_configuration(self):
        """Test case for get_email_configuration

        Retrieve the current email configuration  # noqa: E501
        """
        pass

    def test_set_email_configuration(self):
        """Test case for set_email_configuration

        Set the current email configuration  # noqa: E501
        """
        pass

    def test_test_email_configuration(self):
        """Test case for test_email_configuration

        Send a test email to the email address provided in the request body  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
