"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nxrm_sdk
from nxrm_sdk.models.base_tag_xo import BaseTagXO  # noqa: E501
from nxrm_sdk.rest import ApiException


class TestBaseTagXO(unittest.TestCase):
    """BaseTagXO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseTagXO(self):
        """Test BaseTagXO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.base_tag_xo.BaseTagXO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
