# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.api.security_management_roles_api import SecurityManagementRolesApi  # noqa: E501
from nexus_sdk.rest import ApiException


class TestSecurityManagementRolesApi(unittest.TestCase):
    """SecurityManagementRolesApi unit test stubs"""

    def setUp(self):
        self.api = SecurityManagementRolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        Create role  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete role  # noqa: E501
        """
        pass

    def test_get_role(self):
        """Test case for get_role

        Get role  # noqa: E501
        """
        pass

    def test_get_roles(self):
        """Test case for get_roles

        List roles  # noqa: E501
        """
        pass

    def test_update1(self):
        """Test case for update1

        Update role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
