"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nxrm_sdk
from nxrm_sdk.api.blob_store_api import BlobStoreApi  # noqa: E501
from nxrm_sdk.rest import ApiException


class TestBlobStoreApi(unittest.TestCase):
    """BlobStoreApi unit test stubs"""

    def setUp(self):
        self.api = BlobStoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_convert_blob_store_to_group(self):
        """Test case for convert_blob_store_to_group

        Convert a blob store to a group blob store  # noqa: E501
        """
        pass

    def test_create_blob_store(self):
        """Test case for create_blob_store

        Create an S3 blob store  # noqa: E501
        """
        pass

    def test_create_blob_store1(self):
        """Test case for create_blob_store1

        Create an Azure blob store  # noqa: E501
        """
        pass

    def test_create_file_blob_store(self):
        """Test case for create_file_blob_store

        Create a file blob store  # noqa: E501
        """
        pass

    def test_create_group_blob_store(self):
        """Test case for create_group_blob_store

        Create a group blob store  # noqa: E501
        """
        pass

    def test_delete_blob_store(self):
        """Test case for delete_blob_store

        Delete a blob store by name  # noqa: E501
        """
        pass

    def test_get_blob_store(self):
        """Test case for get_blob_store

        Get a S3 blob store configuration by name  # noqa: E501
        """
        pass

    def test_get_blob_store1(self):
        """Test case for get_blob_store1

        Get an Azure blob store configuration by name  # noqa: E501
        """
        pass

    def test_get_file_blob_store_configuration(self):
        """Test case for get_file_blob_store_configuration

        Get a file blob store configuration by name  # noqa: E501
        """
        pass

    def test_get_group_blob_store_configuration(self):
        """Test case for get_group_blob_store_configuration

        Get a group blob store configuration by name  # noqa: E501
        """
        pass

    def test_list_blob_stores(self):
        """Test case for list_blob_stores

        List the blob stores  # noqa: E501
        """
        pass

    def test_quota_status(self):
        """Test case for quota_status

        Get quota status for a given blob store  # noqa: E501
        """
        pass

    def test_update_blob_store(self):
        """Test case for update_blob_store

        Update an S3 blob store configuration by name  # noqa: E501
        """
        pass

    def test_update_blob_store1(self):
        """Test case for update_blob_store1

        Update an Azure blob store configuration by name  # noqa: E501
        """
        pass

    def test_update_file_blob_store(self):
        """Test case for update_file_blob_store

        Update a file blob store configuration by name  # noqa: E501
        """
        pass

    def test_update_group_blob_store(self):
        """Test case for update_group_blob_store

        Update a group blob store configuration by name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
