# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nxrm_sdk
from nxrm_sdk.models.api_certificate import ApiCertificate  # noqa: E501
from nxrm_sdk.rest import ApiException


class TestApiCertificate(unittest.TestCase):
    """ApiCertificate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiCertificate(self):
        """Test ApiCertificate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_certificate.ApiCertificate()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
