# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nxrm_sdk
from nxrm_sdk.api.security_management_anonymous_access_api import (  # noqa: E501
    SecurityManagementAnonymousAccessApi,
)
from nxrm_sdk.rest import ApiException


class TestSecurityManagementAnonymousAccessApi(unittest.TestCase):
    """SecurityManagementAnonymousAccessApi unit test stubs"""

    def setUp(self):
        self.api = SecurityManagementAnonymousAccessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read(self):
        """Test case for read

        Get Anonymous Access settings  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update Anonymous Access settings  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
