"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nxrm_sdk
from nxrm_sdk.models.docker_group_repository_api_request import (  # noqa: E501
    DockerGroupRepositoryApiRequest,
)
from nxrm_sdk.rest import ApiException


class TestDockerGroupRepositoryApiRequest(unittest.TestCase):
    """DockerGroupRepositoryApiRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDockerGroupRepositoryApiRequest(self):
        """Test DockerGroupRepositoryApiRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.docker_group_repository_api_request.DockerGroupRepositoryApiRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
