# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nxrm_sdk
from nxrm_sdk.api.replication_api import ReplicationApi  # noqa: E501
from nxrm_sdk.rest import ApiException


class TestReplicationApi(unittest.TestCase):
    """ReplicationApi unit test stubs"""

    def setUp(self):
        self.api = ReplicationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create2(self):
        """Test case for create2

        Create a replication connection.  # noqa: E501
        """
        pass

    def test_delete3(self):
        """Test case for delete3

        Delete a replication connection.  # noqa: E501
        """
        pass

    def test_disable(self):
        """Test case for disable

        Disable replication on a target repository..  # noqa: E501
        """
        pass

    def test_enable(self):
        """Test case for enable

        Enable replication on a target repository.  # noqa: E501
        """
        pass

    def test_get4(self):
        """Test case for get4

        Fetch a replication connection.  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        List the replication connections.  # noqa: E501
        """
        pass

    def test_update2(self):
        """Test case for update2

        Update a replication connection.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
