# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nxrm_sdk
from nxrm_sdk.models.s3_blob_store_api_model import S3BlobStoreApiModel  # noqa: E501
from nxrm_sdk.rest import ApiException


class TestS3BlobStoreApiModel(unittest.TestCase):
    """S3BlobStoreApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3BlobStoreApiModel(self):
        """Test S3BlobStoreApiModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.s3_blob_store_api_model.S3BlobStoreApiModel()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
