"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nxrm_sdk
from nxrm_sdk.api.content_selectors_api import ContentSelectorsApi  # noqa: E501
from nxrm_sdk.rest import ApiException


class TestContentSelectorsApi(unittest.TestCase):
    """ContentSelectorsApi unit test stubs"""

    def setUp(self):
        self.api = ContentSelectorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_content_selector(self):
        """Test case for create_content_selector

        Create a new content selector  # noqa: E501
        """
        pass

    def test_delete_content_selector(self):
        """Test case for delete_content_selector

        Delete a content selector  # noqa: E501
        """
        pass

    def test_get_content_selector(self):
        """Test case for get_content_selector

        Get a content selector by name  # noqa: E501
        """
        pass

    def test_get_content_selectors(self):
        """Test case for get_content_selectors

        List content selectors  # noqa: E501
        """
        pass

    def test_update_content_selector(self):
        """Test case for update_content_selector

        Update a content selector  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
