"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nxrm_sdk
from nxrm_sdk.models.tag_xo import TagXO  # noqa: E501
from nxrm_sdk.rest import ApiException


class TestTagXO(unittest.TestCase):
    """TagXO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagXO(self):
        """Test TagXO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tag_xo.TagXO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
