# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nxrm_sdk
from nxrm_sdk.api.security_atlassian_crowd_api import (  # noqa: E501
    SecurityAtlassianCrowdApi,
)
from nxrm_sdk.rest import ApiException


class TestSecurityAtlassianCrowdApi(unittest.TestCase):
    """SecurityAtlassianCrowdApi unit test stubs"""

    def setUp(self):
        self.api = SecurityAtlassianCrowdApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clear_cache(self):
        """Test case for clear_cache

        Clear Atlassian Crowd cache  # noqa: E501
        """
        pass

    def test_read_settings(self):
        """Test case for read_settings

        Retrieve Atlassian Crowd settings configured in Nexus Repository Manager  # noqa: E501
        """
        pass

    def test_update_settings(self):
        """Test case for update_settings

        Update Atlassian Crowd settings configured in Nexus Repository Manager  # noqa: E501
        """
        pass

    def test_verify_connection1(self):
        """Test case for verify_connection1

        Verify connection using supplied Atlassian Crowd settings  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
