# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.models.api_user_source import ApiUserSource  # noqa: E501
from nexus_sdk.rest import ApiException


class TestApiUserSource(unittest.TestCase):
    """ApiUserSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiUserSource(self):
        """Test ApiUserSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_user_source.ApiUserSource()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
