# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.api.security_management_privileges_api import SecurityManagementPrivilegesApi  # noqa: E501
from nexus_sdk.rest import ApiException


class TestSecurityManagementPrivilegesApi(unittest.TestCase):
    """SecurityManagementPrivilegesApi unit test stubs"""

    def setUp(self):
        self.api = SecurityManagementPrivilegesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_privilege(self):
        """Test case for create_privilege

        Create an application type privilege.  # noqa: E501
        """
        pass

    def test_create_privilege1(self):
        """Test case for create_privilege1

        Create a wildcard type privilege.  # noqa: E501
        """
        pass

    def test_create_privilege2(self):
        """Test case for create_privilege2

        Create a repository content selector type privilege.  # noqa: E501
        """
        pass

    def test_create_privilege3(self):
        """Test case for create_privilege3

        Create a repository admin type privilege.  # noqa: E501
        """
        pass

    def test_create_privilege4(self):
        """Test case for create_privilege4

        Create a repository view type privilege.  # noqa: E501
        """
        pass

    def test_create_privilege5(self):
        """Test case for create_privilege5

        Create a script type privilege.  # noqa: E501
        """
        pass

    def test_delete_privilege(self):
        """Test case for delete_privilege

        Delete a privilege by name.  # noqa: E501
        """
        pass

    def test_get_privilege(self):
        """Test case for get_privilege

        Retrieve a privilege by name.  # noqa: E501
        """
        pass

    def test_get_privileges(self):
        """Test case for get_privileges

        Retrieve a list of privileges.  # noqa: E501
        """
        pass

    def test_update_privilege(self):
        """Test case for update_privilege

        Update an application type privilege.  # noqa: E501
        """
        pass

    def test_update_privilege1(self):
        """Test case for update_privilege1

        Update a wildcard type privilege.  # noqa: E501
        """
        pass

    def test_update_privilege2(self):
        """Test case for update_privilege2

        Update a repository view type privilege.  # noqa: E501
        """
        pass

    def test_update_privilege3(self):
        """Test case for update_privilege3

        Update a repository content selector type privilege.  # noqa: E501
        """
        pass

    def test_update_privilege4(self):
        """Test case for update_privilege4

        Update a repository admin type privilege.  # noqa: E501
        """
        pass

    def test_update_privilege5(self):
        """Test case for update_privilege5

        Update a script type privilege.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
