# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.api.script_api import ScriptApi  # noqa: E501
from nexus_sdk.rest import ApiException


class TestScriptApi(unittest.TestCase):
    """ScriptApi unit test stubs"""

    def setUp(self):
        self.api = ScriptApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add(self):
        """Test case for add

        Add a new script  # noqa: E501
        """
        pass

    def test_browse(self):
        """Test case for browse

        List all stored scripts  # noqa: E501
        """
        pass

    def test_delete1(self):
        """Test case for delete1

        Delete stored script by name  # noqa: E501
        """
        pass

    def test_edit(self):
        """Test case for edit

        Update stored script by name  # noqa: E501
        """
        pass

    def test_read1(self):
        """Test case for read1

        Read stored script by name  # noqa: E501
        """
        pass

    def test_run1(self):
        """Test case for run1

        Run stored script by name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
