"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nxrm_sdk
from nxrm_sdk.models.s3_blob_store_api_encryption import (  # noqa: E501
    S3BlobStoreApiEncryption,
)
from nxrm_sdk.rest import ApiException


class TestS3BlobStoreApiEncryption(unittest.TestCase):
    """S3BlobStoreApiEncryption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3BlobStoreApiEncryption(self):
        """Test S3BlobStoreApiEncryption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.s3_blob_store_api_encryption.S3BlobStoreApiEncryption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
