"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nxrm_sdk
from nxrm_sdk.models.api_privilege import ApiPrivilege  # noqa: E501
from nxrm_sdk.rest import ApiException


class TestApiPrivilege(unittest.TestCase):
    """ApiPrivilege unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiPrivilege(self):
        """Test ApiPrivilege"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_privilege.ApiPrivilege()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
