# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nxrm_sdk
from nxrm_sdk.models.api_privilege_repository_admin_request import (  # noqa: E501
    ApiPrivilegeRepositoryAdminRequest,
)
from nxrm_sdk.rest import ApiException


class TestApiPrivilegeRepositoryAdminRequest(unittest.TestCase):
    """ApiPrivilegeRepositoryAdminRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiPrivilegeRepositoryAdminRequest(self):
        """Test ApiPrivilegeRepositoryAdminRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_privilege_repository_admin_request.ApiPrivilegeRepositoryAdminRequest()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
