# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.models.nuget_group_repository_api_request import (  # noqa: E501
    NugetGroupRepositoryApiRequest,
)
from nexus_sdk.rest import ApiException


class TestNugetGroupRepositoryApiRequest(unittest.TestCase):
    """NugetGroupRepositoryApiRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNugetGroupRepositoryApiRequest(self):
        """Test NugetGroupRepositoryApiRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.nuget_group_repository_api_request.NugetGroupRepositoryApiRequest()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
