"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nxrm_sdk
from nxrm_sdk.api.staging_api import StagingApi  # noqa: E501
from nxrm_sdk.rest import ApiException


class TestStagingApi(unittest.TestCase):
    """StagingApi unit test stubs"""

    def setUp(self):
        self.api = StagingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete4(self):
        """Test case for delete4

        Delete components  # noqa: E501
        """
        pass

    def test_move(self):
        """Test case for move

        Move components  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
