# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.models.npm_hosted_repository_api_request import NpmHostedRepositoryApiRequest  # noqa: E501
from nexus_sdk.rest import ApiException


class TestNpmHostedRepositoryApiRequest(unittest.TestCase):
    """NpmHostedRepositoryApiRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNpmHostedRepositoryApiRequest(self):
        """Test NpmHostedRepositoryApiRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.npm_hosted_repository_api_request.NpmHostedRepositoryApiRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
