# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.api.status_api import StatusApi  # noqa: E501
from nexus_sdk.rest import ApiException


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_system_status_checks(self):
        """Test case for get_system_status_checks

        Health check endpoint that returns the results of the system status checks  # noqa: E501
        """
        pass

    def test_is_available(self):
        """Test case for is_available

        Health check endpoint that validates server can respond to read requests  # noqa: E501
        """
        pass

    def test_is_writable(self):
        """Test case for is_writable

        Health check endpoint that validates server can respond to read and write requests  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
