# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.api.security_management_saml_api import (  # noqa: E501
    SecurityManagementSAMLApi,
)
from nexus_sdk.rest import ApiException


class TestSecurityManagementSAMLApi(unittest.TestCase):
    """SecurityManagementSAMLApi unit test stubs"""

    def setUp(self):
        self.api = SecurityManagementSAMLApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_saml_configuration(self):
        """Test case for delete_saml_configuration

        Delete SAML configuration  # noqa: E501
        """
        pass

    def test_get_metadata(self):
        """Test case for get_metadata

        Get service provider metadata XML document  # noqa: E501
        """
        pass

    def test_get_public_certificate_in_pem_format(self):
        """Test case for get_public_certificate_in_pem_format

        Get service provider signing certificate in PEM format  # noqa: E501
        """
        pass

    def test_get_saml_configuration(self):
        """Test case for get_saml_configuration

        Get SAML configuration  # noqa: E501
        """
        pass

    def test_put_saml_configuration(self):
        """Test case for put_saml_configuration

        Create or update SAML configuration  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
