# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.api.security_management_jwt_api import (  # noqa: E501
    SecurityManagementJWTApi,
)
from nexus_sdk.rest import ApiException


class TestSecurityManagementJWTApi(unittest.TestCase):
    """SecurityManagementJWTApi unit test stubs"""

    def setUp(self):
        self.api = SecurityManagementJWTApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reset_secret(self):
        """Test case for reset_secret

        Reset JWT secret (note that session will be expired for the all logged-in users)  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
