# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.models.simple_api_proxy_repository import (  # noqa: E501
    SimpleApiProxyRepository,
)
from nexus_sdk.rest import ApiException


class TestSimpleApiProxyRepository(unittest.TestCase):
    """SimpleApiProxyRepository unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimpleApiProxyRepository(self):
        """Test SimpleApiProxyRepository"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.simple_api_proxy_repository.SimpleApiProxyRepository()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
