# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_sdk
from nexus_sdk.api.routing_rules_api import RoutingRulesApi  # noqa: E501
from nexus_sdk.rest import ApiException


class TestRoutingRulesApi(unittest.TestCase):
    """RoutingRulesApi unit test stubs"""

    def setUp(self):
        self.api = RoutingRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_routing_rule(self):
        """Test case for create_routing_rule

        Create a single routing rule  # noqa: E501
        """
        pass

    def test_delete_routing_rule(self):
        """Test case for delete_routing_rule

        Delete a single routing rule  # noqa: E501
        """
        pass

    def test_get_routing_rule(self):
        """Test case for get_routing_rule

        Get a single routing rule  # noqa: E501
        """
        pass

    def test_get_routing_rules(self):
        """Test case for get_routing_rules

        List routing rules  # noqa: E501
        """
        pass

    def test_update_routing_rule(self):
        """Test case for update_routing_rule

        Update a single routing rule  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
