"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nxrm_sdk
from nxrm_sdk.models.npm_group_repository_api_request import (  # noqa: E501
    NpmGroupRepositoryApiRequest,
)
from nxrm_sdk.rest import ApiException


class TestNpmGroupRepositoryApiRequest(unittest.TestCase):
    """NpmGroupRepositoryApiRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNpmGroupRepositoryApiRequest(self):
        """Test NpmGroupRepositoryApiRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.npm_group_repository_api_request.NpmGroupRepositoryApiRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
