# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from nxrm_sdk.api_client import ApiClient


class TagsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def associate(self, tag_name, **kwargs):  # noqa: E501
        """Associate components with a tag  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.associate(tag_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tag_name: Tag to associate to the matched components (required)
        :param bool wait: The query waits until the indexing is complete
        :param str q: Query by keyword
        :param str repository: Repository name
        :param str format: Query by format
        :param str group: Component group
        :param str name: Component name
        :param str version: Component version
        :param str prerelease: Prerelease version flag
        :param str md5: Specific MD5 hash of component's asset
        :param str sha1: Specific SHA-1 hash of component's asset
        :param str sha256: Specific SHA-256 hash of component's asset
        :param str sha512: Specific SHA-512 hash of component's asset
        :param str conan_base_version: Conan base version
        :param str conan_channel: Conan channel
        :param str docker_image_name: Docker image name
        :param str docker_image_tag: Docker image tag
        :param str docker_layer_id: Docker layer ID
        :param str docker_content_digest: Docker content digest
        :param str maven_group_id: Maven groupId
        :param str maven_artifact_id: Maven artifactId
        :param str maven_base_version: Maven base version
        :param str maven_extension: Maven extension of component's asset
        :param str maven_classifier: Maven classifier of component's asset
        :param str npm_scope: npm scope
        :param str nuget_id: NuGet id
        :param str nuget_tags: NuGet tags
        :param str p2_plugin_name: p2 plugin name
        :param str pypi_classifiers: PyPI classifiers
        :param str pypi_description: PyPI description
        :param str pypi_keywords: PyPI keywords
        :param str pypi_summary: PyPI summary
        :param str rubygems_description: RubyGems description
        :param str rubygems_platform: RubyGems platform
        :param str rubygems_summary: RubyGems summary
        :param str tag: Component tag
        :param str yum_architecture: Yum architecture
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.associate_with_http_info(tag_name, **kwargs)  # noqa: E501
        else:
            (data) = self.associate_with_http_info(tag_name, **kwargs)  # noqa: E501
            return data

    def associate_with_http_info(self, tag_name, **kwargs):  # noqa: E501
        """Associate components with a tag  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.associate_with_http_info(tag_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tag_name: Tag to associate to the matched components (required)
        :param bool wait: The query waits until the indexing is complete
        :param str q: Query by keyword
        :param str repository: Repository name
        :param str format: Query by format
        :param str group: Component group
        :param str name: Component name
        :param str version: Component version
        :param str prerelease: Prerelease version flag
        :param str md5: Specific MD5 hash of component's asset
        :param str sha1: Specific SHA-1 hash of component's asset
        :param str sha256: Specific SHA-256 hash of component's asset
        :param str sha512: Specific SHA-512 hash of component's asset
        :param str conan_base_version: Conan base version
        :param str conan_channel: Conan channel
        :param str docker_image_name: Docker image name
        :param str docker_image_tag: Docker image tag
        :param str docker_layer_id: Docker layer ID
        :param str docker_content_digest: Docker content digest
        :param str maven_group_id: Maven groupId
        :param str maven_artifact_id: Maven artifactId
        :param str maven_base_version: Maven base version
        :param str maven_extension: Maven extension of component's asset
        :param str maven_classifier: Maven classifier of component's asset
        :param str npm_scope: npm scope
        :param str nuget_id: NuGet id
        :param str nuget_tags: NuGet tags
        :param str p2_plugin_name: p2 plugin name
        :param str pypi_classifiers: PyPI classifiers
        :param str pypi_description: PyPI description
        :param str pypi_keywords: PyPI keywords
        :param str pypi_summary: PyPI summary
        :param str rubygems_description: RubyGems description
        :param str rubygems_platform: RubyGems platform
        :param str rubygems_summary: RubyGems summary
        :param str tag: Component tag
        :param str yum_architecture: Yum architecture
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "tag_name",
            "wait",
            "q",
            "repository",
            "format",
            "group",
            "name",
            "version",
            "prerelease",
            "md5",
            "sha1",
            "sha256",
            "sha512",
            "conan_base_version",
            "conan_channel",
            "docker_image_name",
            "docker_image_tag",
            "docker_layer_id",
            "docker_content_digest",
            "maven_group_id",
            "maven_artifact_id",
            "maven_base_version",
            "maven_extension",
            "maven_classifier",
            "npm_scope",
            "nuget_id",
            "nuget_tags",
            "p2_plugin_name",
            "pypi_classifiers",
            "pypi_description",
            "pypi_keywords",
            "pypi_summary",
            "rubygems_description",
            "rubygems_platform",
            "rubygems_summary",
            "tag",
            "yum_architecture",
        ]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method associate" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'tag_name' is set
        if "tag_name" not in params or params["tag_name"] is None:
            raise ValueError(
                "Missing the required parameter `tag_name` when calling `associate`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "tag_name" in params:
            path_params["tagName"] = params["tag_name"]  # noqa: E501

        query_params = []
        if "wait" in params:
            query_params.append(("wait", params["wait"]))  # noqa: E501
        if "q" in params:
            query_params.append(("q", params["q"]))  # noqa: E501
        if "repository" in params:
            query_params.append(("repository", params["repository"]))  # noqa: E501
        if "format" in params:
            query_params.append(("format", params["format"]))  # noqa: E501
        if "group" in params:
            query_params.append(("group", params["group"]))  # noqa: E501
        if "name" in params:
            query_params.append(("name", params["name"]))  # noqa: E501
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501
        if "prerelease" in params:
            query_params.append(("prerelease", params["prerelease"]))  # noqa: E501
        if "md5" in params:
            query_params.append(("md5", params["md5"]))  # noqa: E501
        if "sha1" in params:
            query_params.append(("sha1", params["sha1"]))  # noqa: E501
        if "sha256" in params:
            query_params.append(("sha256", params["sha256"]))  # noqa: E501
        if "sha512" in params:
            query_params.append(("sha512", params["sha512"]))  # noqa: E501
        if "conan_base_version" in params:
            query_params.append(
                ("conan.baseVersion", params["conan_base_version"])
            )  # noqa: E501
        if "conan_channel" in params:
            query_params.append(
                ("conan.channel", params["conan_channel"])
            )  # noqa: E501
        if "docker_image_name" in params:
            query_params.append(
                ("docker.imageName", params["docker_image_name"])
            )  # noqa: E501
        if "docker_image_tag" in params:
            query_params.append(
                ("docker.imageTag", params["docker_image_tag"])
            )  # noqa: E501
        if "docker_layer_id" in params:
            query_params.append(
                ("docker.layerId", params["docker_layer_id"])
            )  # noqa: E501
        if "docker_content_digest" in params:
            query_params.append(
                ("docker.contentDigest", params["docker_content_digest"])
            )  # noqa: E501
        if "maven_group_id" in params:
            query_params.append(
                ("maven.groupId", params["maven_group_id"])
            )  # noqa: E501
        if "maven_artifact_id" in params:
            query_params.append(
                ("maven.artifactId", params["maven_artifact_id"])
            )  # noqa: E501
        if "maven_base_version" in params:
            query_params.append(
                ("maven.baseVersion", params["maven_base_version"])
            )  # noqa: E501
        if "maven_extension" in params:
            query_params.append(
                ("maven.extension", params["maven_extension"])
            )  # noqa: E501
        if "maven_classifier" in params:
            query_params.append(
                ("maven.classifier", params["maven_classifier"])
            )  # noqa: E501
        if "npm_scope" in params:
            query_params.append(("npm.scope", params["npm_scope"]))  # noqa: E501
        if "nuget_id" in params:
            query_params.append(("nuget.id", params["nuget_id"]))  # noqa: E501
        if "nuget_tags" in params:
            query_params.append(("nuget.tags", params["nuget_tags"]))  # noqa: E501
        if "p2_plugin_name" in params:
            query_params.append(
                ("p2.pluginName", params["p2_plugin_name"])
            )  # noqa: E501
        if "pypi_classifiers" in params:
            query_params.append(
                ("pypi.classifiers", params["pypi_classifiers"])
            )  # noqa: E501
        if "pypi_description" in params:
            query_params.append(
                ("pypi.description", params["pypi_description"])
            )  # noqa: E501
        if "pypi_keywords" in params:
            query_params.append(
                ("pypi.keywords", params["pypi_keywords"])
            )  # noqa: E501
        if "pypi_summary" in params:
            query_params.append(("pypi.summary", params["pypi_summary"]))  # noqa: E501
        if "rubygems_description" in params:
            query_params.append(
                ("rubygems.description", params["rubygems_description"])
            )  # noqa: E501
        if "rubygems_platform" in params:
            query_params.append(
                ("rubygems.platform", params["rubygems_platform"])
            )  # noqa: E501
        if "rubygems_summary" in params:
            query_params.append(
                ("rubygems.summary", params["rubygems_summary"])
            )  # noqa: E501
        if "tag" in params:
            query_params.append(("tag", params["tag"]))  # noqa: E501
        if "yum_architecture" in params:
            query_params.append(
                ("yum.architecture", params["yum_architecture"])
            )  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            "/v1/tags/associate/{tagName}",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def create1(self, **kwargs):  # noqa: E501
        """Create a tag  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create1(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TagXO body:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.create1_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create1_with_http_info(**kwargs)  # noqa: E501
            return data

    def create1_with_http_info(self, **kwargs):  # noqa: E501
        """Create a tag  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create1_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TagXO body:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["body"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'" " to method create1" % key
                )
            params[key] = val
        del params["kwargs"]

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Content-Type`
        header_params[
            "Content-Type"
        ] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            "/v1/tags",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def delete2(self, name, **kwargs):  # noqa: E501
        """Delete a tag  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete2(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.delete2_with_http_info(name, **kwargs)  # noqa: E501
        else:
            (data) = self.delete2_with_http_info(name, **kwargs)  # noqa: E501
            return data

    def delete2_with_http_info(self, name, **kwargs):  # noqa: E501
        """Delete a tag  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete2_with_http_info(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["name"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'" " to method delete2" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'name' is set
        if "name" not in params or params["name"] is None:
            raise ValueError(
                "Missing the required parameter `name` when calling `delete2`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "name" in params:
            path_params["name"] = params["name"]  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            "/v1/tags/{name}",
            "DELETE",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def disassociate(self, tag_name, **kwargs):  # noqa: E501
        """Disassociate components from a tag  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.disassociate(tag_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tag_name: Tag to associate to the matched components (required)
        :param str q: Query by keyword
        :param str repository: Repository name
        :param str format: Query by format
        :param str group: Component group
        :param str name: Component name
        :param str version: Component version
        :param str prerelease: Prerelease version flag
        :param str md5: Specific MD5 hash of component's asset
        :param str sha1: Specific SHA-1 hash of component's asset
        :param str sha256: Specific SHA-256 hash of component's asset
        :param str sha512: Specific SHA-512 hash of component's asset
        :param str conan_base_version: Conan base version
        :param str conan_channel: Conan channel
        :param str docker_image_name: Docker image name
        :param str docker_image_tag: Docker image tag
        :param str docker_layer_id: Docker layer ID
        :param str docker_content_digest: Docker content digest
        :param str maven_group_id: Maven groupId
        :param str maven_artifact_id: Maven artifactId
        :param str maven_base_version: Maven base version
        :param str maven_extension: Maven extension of component's asset
        :param str maven_classifier: Maven classifier of component's asset
        :param str npm_scope: npm scope
        :param str nuget_id: NuGet id
        :param str nuget_tags: NuGet tags
        :param str p2_plugin_name: p2 plugin name
        :param str pypi_classifiers: PyPI classifiers
        :param str pypi_description: PyPI description
        :param str pypi_keywords: PyPI keywords
        :param str pypi_summary: PyPI summary
        :param str rubygems_description: RubyGems description
        :param str rubygems_platform: RubyGems platform
        :param str rubygems_summary: RubyGems summary
        :param str tag: Component tag
        :param str yum_architecture: Yum architecture
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.disassociate_with_http_info(tag_name, **kwargs)  # noqa: E501
        else:
            (data) = self.disassociate_with_http_info(tag_name, **kwargs)  # noqa: E501
            return data

    def disassociate_with_http_info(self, tag_name, **kwargs):  # noqa: E501
        """Disassociate components from a tag  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.disassociate_with_http_info(tag_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tag_name: Tag to associate to the matched components (required)
        :param str q: Query by keyword
        :param str repository: Repository name
        :param str format: Query by format
        :param str group: Component group
        :param str name: Component name
        :param str version: Component version
        :param str prerelease: Prerelease version flag
        :param str md5: Specific MD5 hash of component's asset
        :param str sha1: Specific SHA-1 hash of component's asset
        :param str sha256: Specific SHA-256 hash of component's asset
        :param str sha512: Specific SHA-512 hash of component's asset
        :param str conan_base_version: Conan base version
        :param str conan_channel: Conan channel
        :param str docker_image_name: Docker image name
        :param str docker_image_tag: Docker image tag
        :param str docker_layer_id: Docker layer ID
        :param str docker_content_digest: Docker content digest
        :param str maven_group_id: Maven groupId
        :param str maven_artifact_id: Maven artifactId
        :param str maven_base_version: Maven base version
        :param str maven_extension: Maven extension of component's asset
        :param str maven_classifier: Maven classifier of component's asset
        :param str npm_scope: npm scope
        :param str nuget_id: NuGet id
        :param str nuget_tags: NuGet tags
        :param str p2_plugin_name: p2 plugin name
        :param str pypi_classifiers: PyPI classifiers
        :param str pypi_description: PyPI description
        :param str pypi_keywords: PyPI keywords
        :param str pypi_summary: PyPI summary
        :param str rubygems_description: RubyGems description
        :param str rubygems_platform: RubyGems platform
        :param str rubygems_summary: RubyGems summary
        :param str tag: Component tag
        :param str yum_architecture: Yum architecture
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "tag_name",
            "q",
            "repository",
            "format",
            "group",
            "name",
            "version",
            "prerelease",
            "md5",
            "sha1",
            "sha256",
            "sha512",
            "conan_base_version",
            "conan_channel",
            "docker_image_name",
            "docker_image_tag",
            "docker_layer_id",
            "docker_content_digest",
            "maven_group_id",
            "maven_artifact_id",
            "maven_base_version",
            "maven_extension",
            "maven_classifier",
            "npm_scope",
            "nuget_id",
            "nuget_tags",
            "p2_plugin_name",
            "pypi_classifiers",
            "pypi_description",
            "pypi_keywords",
            "pypi_summary",
            "rubygems_description",
            "rubygems_platform",
            "rubygems_summary",
            "tag",
            "yum_architecture",
        ]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method disassociate" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'tag_name' is set
        if "tag_name" not in params or params["tag_name"] is None:
            raise ValueError(
                "Missing the required parameter `tag_name` when calling `disassociate`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "tag_name" in params:
            path_params["tagName"] = params["tag_name"]  # noqa: E501

        query_params = []
        if "q" in params:
            query_params.append(("q", params["q"]))  # noqa: E501
        if "repository" in params:
            query_params.append(("repository", params["repository"]))  # noqa: E501
        if "format" in params:
            query_params.append(("format", params["format"]))  # noqa: E501
        if "group" in params:
            query_params.append(("group", params["group"]))  # noqa: E501
        if "name" in params:
            query_params.append(("name", params["name"]))  # noqa: E501
        if "version" in params:
            query_params.append(("version", params["version"]))  # noqa: E501
        if "prerelease" in params:
            query_params.append(("prerelease", params["prerelease"]))  # noqa: E501
        if "md5" in params:
            query_params.append(("md5", params["md5"]))  # noqa: E501
        if "sha1" in params:
            query_params.append(("sha1", params["sha1"]))  # noqa: E501
        if "sha256" in params:
            query_params.append(("sha256", params["sha256"]))  # noqa: E501
        if "sha512" in params:
            query_params.append(("sha512", params["sha512"]))  # noqa: E501
        if "conan_base_version" in params:
            query_params.append(
                ("conan.baseVersion", params["conan_base_version"])
            )  # noqa: E501
        if "conan_channel" in params:
            query_params.append(
                ("conan.channel", params["conan_channel"])
            )  # noqa: E501
        if "docker_image_name" in params:
            query_params.append(
                ("docker.imageName", params["docker_image_name"])
            )  # noqa: E501
        if "docker_image_tag" in params:
            query_params.append(
                ("docker.imageTag", params["docker_image_tag"])
            )  # noqa: E501
        if "docker_layer_id" in params:
            query_params.append(
                ("docker.layerId", params["docker_layer_id"])
            )  # noqa: E501
        if "docker_content_digest" in params:
            query_params.append(
                ("docker.contentDigest", params["docker_content_digest"])
            )  # noqa: E501
        if "maven_group_id" in params:
            query_params.append(
                ("maven.groupId", params["maven_group_id"])
            )  # noqa: E501
        if "maven_artifact_id" in params:
            query_params.append(
                ("maven.artifactId", params["maven_artifact_id"])
            )  # noqa: E501
        if "maven_base_version" in params:
            query_params.append(
                ("maven.baseVersion", params["maven_base_version"])
            )  # noqa: E501
        if "maven_extension" in params:
            query_params.append(
                ("maven.extension", params["maven_extension"])
            )  # noqa: E501
        if "maven_classifier" in params:
            query_params.append(
                ("maven.classifier", params["maven_classifier"])
            )  # noqa: E501
        if "npm_scope" in params:
            query_params.append(("npm.scope", params["npm_scope"]))  # noqa: E501
        if "nuget_id" in params:
            query_params.append(("nuget.id", params["nuget_id"]))  # noqa: E501
        if "nuget_tags" in params:
            query_params.append(("nuget.tags", params["nuget_tags"]))  # noqa: E501
        if "p2_plugin_name" in params:
            query_params.append(
                ("p2.pluginName", params["p2_plugin_name"])
            )  # noqa: E501
        if "pypi_classifiers" in params:
            query_params.append(
                ("pypi.classifiers", params["pypi_classifiers"])
            )  # noqa: E501
        if "pypi_description" in params:
            query_params.append(
                ("pypi.description", params["pypi_description"])
            )  # noqa: E501
        if "pypi_keywords" in params:
            query_params.append(
                ("pypi.keywords", params["pypi_keywords"])
            )  # noqa: E501
        if "pypi_summary" in params:
            query_params.append(("pypi.summary", params["pypi_summary"]))  # noqa: E501
        if "rubygems_description" in params:
            query_params.append(
                ("rubygems.description", params["rubygems_description"])
            )  # noqa: E501
        if "rubygems_platform" in params:
            query_params.append(
                ("rubygems.platform", params["rubygems_platform"])
            )  # noqa: E501
        if "rubygems_summary" in params:
            query_params.append(
                ("rubygems.summary", params["rubygems_summary"])
            )  # noqa: E501
        if "tag" in params:
            query_params.append(("tag", params["tag"]))  # noqa: E501
        if "yum_architecture" in params:
            query_params.append(
                ("yum.architecture", params["yum_architecture"])
            )  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            "/v1/tags/associate/{tagName}",
            "DELETE",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def get3(self, name, **kwargs):  # noqa: E501
        """Get a tag  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get3(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to retrieve (required)
        :return: TagXO
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.get3_with_http_info(name, **kwargs)  # noqa: E501
        else:
            (data) = self.get3_with_http_info(name, **kwargs)  # noqa: E501
            return data

    def get3_with_http_info(self, name, **kwargs):  # noqa: E501
        """Get a tag  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get3_with_http_info(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to retrieve (required)
        :return: TagXO
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["name"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'" " to method get3" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'name' is set
        if "name" not in params or params["name"] is None:
            raise ValueError(
                "Missing the required parameter `name` when calling `get3`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "name" in params:
            path_params["name"] = params["name"]  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            "/v1/tags/{name}",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="TagXO",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def get_tags(self, **kwargs):  # noqa: E501
        """List tags  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tags(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str continuation_token: A token returned by a prior request. If present, the next page of results are returned
        :return: PageTagXO
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.get_tags_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_tags_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_tags_with_http_info(self, **kwargs):  # noqa: E501
        """List tags  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tags_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str continuation_token: A token returned by a prior request. If present, the next page of results are returned
        :return: PageTagXO
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["continuation_token"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tags" % key
                )
            params[key] = val
        del params["kwargs"]

        collection_formats = {}

        path_params = {}

        query_params = []
        if "continuation_token" in params:
            query_params.append(
                ("continuationToken", params["continuation_token"])
            )  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            "/v1/tags",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PageTagXO",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def replace(self, name, **kwargs):  # noqa: E501
        """Update a tags attributes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.replace(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: (required)
        :param BaseTagXO body:
        :return: TagXO
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.replace_with_http_info(name, **kwargs)  # noqa: E501
        else:
            (data) = self.replace_with_http_info(name, **kwargs)  # noqa: E501
            return data

    def replace_with_http_info(self, name, **kwargs):  # noqa: E501
        """Update a tags attributes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.replace_with_http_info(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: (required)
        :param BaseTagXO body:
        :return: TagXO
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["name", "body"]  # noqa: E501
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'" " to method replace" % key
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'name' is set
        if "name" not in params or params["name"] is None:
            raise ValueError(
                "Missing the required parameter `name` when calling `replace`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}
        if "name" in params:
            path_params["name"] = params["name"]  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # HTTP header `Content-Type`
        header_params[
            "Content-Type"
        ] = self.api_client.select_header_content_type(  # noqa: E501
            ["application/json"]
        )  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            "/v1/tags/{name}",
            "PUT",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="TagXO",  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )
