# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.42.0-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RawAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"content_disposition": "str"}

    attribute_map = {"content_disposition": "contentDisposition"}

    def __init__(self, content_disposition=None):  # noqa: E501
        """RawAttributes - a model defined in Swagger"""  # noqa: E501
        self._content_disposition = None
        self.discriminator = None
        if content_disposition is not None:
            self.content_disposition = content_disposition

    @property
    def content_disposition(self):
        """Gets the content_disposition of this RawAttributes.  # noqa: E501

        Content Disposition  # noqa: E501

        :return: The content_disposition of this RawAttributes.  # noqa: E501
        :rtype: str
        """
        return self._content_disposition

    @content_disposition.setter
    def content_disposition(self, content_disposition):
        """Sets the content_disposition of this RawAttributes.

        Content Disposition  # noqa: E501

        :param content_disposition: The content_disposition of this RawAttributes.  # noqa: E501
        :type: str
        """
        allowed_values = ["INLINE", "ATTACHMENT"]  # noqa: E501
        if content_disposition not in allowed_values:
            raise ValueError(
                "Invalid value for `content_disposition` ({0}), must be one of {1}".format(  # noqa: E501
                    content_disposition, allowed_values
                )
            )

        self._content_disposition = content_disposition

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(RawAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RawAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
