# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.42.0-01
    Generated by: https://openapi-generator.tech
"""

import unittest

import nexus_sdk
from nexus_sdk.model.api_privilege_repository_content_selector_request import ApiPrivilegeRepositoryContentSelectorRequest
from nexus_sdk import configuration


class TestApiPrivilegeRepositoryContentSelectorRequest(unittest.TestCase):
    """ApiPrivilegeRepositoryContentSelectorRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
