# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.42.0-01
    Generated by: https://openapi-generator.tech
"""

import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import uuid  # noqa: F401
from datetime import date, datetime  # noqa: F401

import frozendict  # noqa: F401
import typing_extensions  # noqa: F401

from nexus_sdk import schemas  # noqa: F401


class ReplicationEnableXO(schemas.DictSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    class MetaOapg:
        required = {
            "replicationConnectionName",
            "targetRepositoryName",
            "sourceRepositoryName",
        }

        class properties:
            targetRepositoryName = schemas.StrSchema
            replicationConnectionName = schemas.StrSchema
            sourceRepositoryName = schemas.StrSchema
            __annotations__ = {
                "targetRepositoryName": targetRepositoryName,
                "replicationConnectionName": replicationConnectionName,
                "sourceRepositoryName": sourceRepositoryName,
            }

    replicationConnectionName: MetaOapg.properties.replicationConnectionName
    targetRepositoryName: MetaOapg.properties.targetRepositoryName
    sourceRepositoryName: MetaOapg.properties.sourceRepositoryName

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["targetRepositoryName"]
    ) -> MetaOapg.properties.targetRepositoryName:
        ...

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["replicationConnectionName"]
    ) -> MetaOapg.properties.replicationConnectionName:
        ...

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["sourceRepositoryName"]
    ) -> MetaOapg.properties.sourceRepositoryName:
        ...

    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema:
        ...

    def __getitem__(
        self,
        name: typing.Union[
            typing_extensions.Literal[
                "targetRepositoryName",
                "replicationConnectionName",
                "sourceRepositoryName",
            ],
            str,
        ],
    ):
        # dict_instance[name] accessor
        return super().__getitem__(name)

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["targetRepositoryName"]
    ) -> MetaOapg.properties.targetRepositoryName:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["replicationConnectionName"]
    ) -> MetaOapg.properties.replicationConnectionName:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["sourceRepositoryName"]
    ) -> MetaOapg.properties.sourceRepositoryName:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: str
    ) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]:
        ...

    def get_item_oapg(
        self,
        name: typing.Union[
            typing_extensions.Literal[
                "targetRepositoryName",
                "replicationConnectionName",
                "sourceRepositoryName",
            ],
            str,
        ],
    ):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[
            dict,
            frozendict.frozendict,
        ],
        replicationConnectionName: typing.Union[
            MetaOapg.properties.replicationConnectionName,
            str,
        ],
        targetRepositoryName: typing.Union[
            MetaOapg.properties.targetRepositoryName,
            str,
        ],
        sourceRepositoryName: typing.Union[
            MetaOapg.properties.sourceRepositoryName,
            str,
        ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[
            schemas.AnyTypeSchema,
            dict,
            frozendict.frozendict,
            str,
            date,
            datetime,
            uuid.UUID,
            int,
            float,
            decimal.Decimal,
            None,
            list,
            tuple,
            bytes,
        ],
    ) -> "ReplicationEnableXO":
        return super().__new__(
            cls,
            *_args,
            replicationConnectionName=replicationConnectionName,
            targetRepositoryName=targetRepositoryName,
            sourceRepositoryName=sourceRepositoryName,
            _configuration=_configuration,
            **kwargs,
        )
