# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.42.0-01
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from nexus_sdk import schemas  # noqa: F401


class ReplicationAttributes(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "preemptivePullEnabled",
        }
        
        class properties:
            preemptivePullEnabled = schemas.BoolSchema
            assetPathRegex = schemas.StrSchema
            __annotations__ = {
                "preemptivePullEnabled": preemptivePullEnabled,
                "assetPathRegex": assetPathRegex,
            }
    
    preemptivePullEnabled: MetaOapg.properties.preemptivePullEnabled
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["preemptivePullEnabled"]) -> MetaOapg.properties.preemptivePullEnabled: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assetPathRegex"]) -> MetaOapg.properties.assetPathRegex: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["preemptivePullEnabled", "assetPathRegex", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["preemptivePullEnabled"]) -> MetaOapg.properties.preemptivePullEnabled: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assetPathRegex"]) -> typing.Union[MetaOapg.properties.assetPathRegex, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["preemptivePullEnabled", "assetPathRegex", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        preemptivePullEnabled: typing.Union[MetaOapg.properties.preemptivePullEnabled, bool, ],
        assetPathRegex: typing.Union[MetaOapg.properties.assetPathRegex, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReplicationAttributes':
        return super().__new__(
            cls,
            *_args,
            preemptivePullEnabled=preemptivePullEnabled,
            assetPathRegex=assetPathRegex,
            _configuration=_configuration,
            **kwargs,
        )
