# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import nexus_sdk
from nexus_sdk import api_client, configuration, schemas
from nexus_sdk.paths.v1_repositories_rubygems_hosted_repository_name import (  # noqa: E501
    get,
)

from .. import ApiTestMixin


class TestV1RepositoriesRubygemsHostedRepositoryName(ApiTestMixin, unittest.TestCase):
    """
    V1RepositoriesRubygemsHostedRepositoryName unit test stubs
        Get repository  # noqa: E501
    """

    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200


if __name__ == "__main__":
    unittest.main()
