# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.42.0-01
    Generated by: https://openapi-generator.tech
"""

from nexus_sdk.paths.v1_read_only.get import Get
from nexus_sdk.paths.v1_read_only_force_release.post import ForceRelease
from nexus_sdk.paths.v1_read_only_freeze.post import Freeze
from nexus_sdk.paths.v1_read_only_release.post import Release


class ReadOnlyApi(
    ForceRelease,
    Freeze,
    Get,
    Release,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
