# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.42.0-01
    Generated by: https://openapi-generator.tech
"""

from nexus_sdk.paths.v1_security_privileges.get import GetPrivileges
from nexus_sdk.paths.v1_security_privileges_application.post import CreatePrivilege1
from nexus_sdk.paths.v1_security_privileges_application_privilege_name.put import (
    UpdatePrivilege1,
)
from nexus_sdk.paths.v1_security_privileges_privilege_name.delete import DeletePrivilege
from nexus_sdk.paths.v1_security_privileges_privilege_name.get import GetPrivilege
from nexus_sdk.paths.v1_security_privileges_repository_admin.post import (
    CreatePrivilege3,
)
from nexus_sdk.paths.v1_security_privileges_repository_admin_privilege_name.put import (
    UpdatePrivilege4,
)
from nexus_sdk.paths.v1_security_privileges_repository_content_selector.post import (
    CreatePrivilege2,
)
from nexus_sdk.paths.v1_security_privileges_repository_content_selector_privilege_name.put import (
    UpdatePrivilege3,
)
from nexus_sdk.paths.v1_security_privileges_repository_view.post import CreatePrivilege4
from nexus_sdk.paths.v1_security_privileges_repository_view_privilege_name.put import (
    UpdatePrivilege2,
)
from nexus_sdk.paths.v1_security_privileges_script.post import CreatePrivilege5
from nexus_sdk.paths.v1_security_privileges_script_privilege_name.put import (
    UpdatePrivilege5,
)
from nexus_sdk.paths.v1_security_privileges_wildcard.post import CreatePrivilege
from nexus_sdk.paths.v1_security_privileges_wildcard_privilege_name.put import (
    UpdatePrivilege,
)


class SecurityManagementPrivilegesApi(
    CreatePrivilege,
    CreatePrivilege1,
    CreatePrivilege2,
    CreatePrivilege3,
    CreatePrivilege4,
    CreatePrivilege5,
    DeletePrivilege,
    GetPrivilege,
    GetPrivileges,
    UpdatePrivilege,
    UpdatePrivilege1,
    UpdatePrivilege2,
    UpdatePrivilege3,
    UpdatePrivilege4,
    UpdatePrivilege5,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
