# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.42.0-01
    Generated by: https://openapi-generator.tech
"""

from nexus_sdk.paths.v1_security_ldap.get import GetLdapServers
from nexus_sdk.paths.v1_security_ldap.post import CreateLdapServer
from nexus_sdk.paths.v1_security_ldap_change_order.post import ChangeOrder
from nexus_sdk.paths.v1_security_ldap_name.delete import DeleteLdapServer
from nexus_sdk.paths.v1_security_ldap_name.get import GetLdapServer
from nexus_sdk.paths.v1_security_ldap_name.put import UpdateLdapServer


class SecurityManagementLDAPApi(
    ChangeOrder,
    CreateLdapServer,
    DeleteLdapServer,
    GetLdapServer,
    GetLdapServers,
    UpdateLdapServer,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
